server {
    listen 80;

    # Главная страница и API
    location / {
        proxy_pass http://app:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Статические сайты студентов
    # Ссылка будет вида: http://localhost/s/имя/
    location ~ ^/s/(?<project>[^/]+)(?<rest_uri>.*)$ {
        resolver 127.0.0.11 valid=5s;
        
        # Пересылаем запрос в контейнер студента
        proxy_pass http://student-app-$project:80$rest_uri;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        
        # Обработка ошибок, если контейнер не найден
        error_page 502 =404 /404_error;
    }

    location = /404_error {
        return 404 "Сайт не найден или еще запускается...";
    }
}